# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e6920fcf88c8e6a160279cf3b84e57133acbdf8088d344446611baffb024b75ad563a6e3a9abcdd72db5b514dc2879d9572c97cc6d9ef03da009027df234138

test:
  secret_key_base: 3ab6b1473b9087403c5ece1849bc614fdbd03f5bc1f957f30c69778e6a6527873f590da66a4f7b1b1edf6eb78f3a1ddf47ce73e2375068b51f3258c450f00746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
